task/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('viewer.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

viewer/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.index,name='index'),
	path('<int:group_id>/', views.detail, name='detail'),
	path('upload/', views.upload, name='upload'),

]

viewer/models.py
from django.db import models

# Create your models here.
class Group(models.Model):
	group_name = models.CharField(max_length=120,null=True)
	date_created = models.DateTimeField(auto_now_add =False, null=True)

	def __str__(self):
		return (self.group_name)

class Question(models.Model):
	group_id = models.ForeignKey(Group,null=True, on_delete = models.CASCADE)
	question = models.FileField(null=True, blank=True)
	comment = models.CharField(max_length=200)
	created_at = models.CharField(null=True,max_length=200)

	def __str__(self):
		return (self.comment)

viewer/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Group, Question
from django.core.files.storage import FileSystemStorage

# Create your views here.
def index(request):
	if request.user.is_authenticated:

		group_list = Group.objects.all()
		context = {
			'group_list' : group_list
		}
		return render(request, 'index.html', context)
	else:
		return Http404("Please Login to continue")

		
	
def detail(request, group_id):
    question_list = get_object_or_404(Group, pk=group_id)
    return render(request, 'detail.html', {'question_list': question_list})

def upload(request):
	if request.method =='POST':
		uploaded_file = request.FILES['document']
		fs = FileSystemStorage()
		fs.save(uploaded_file.name,uploaded_file)

	return render(request, 'base.html')   

viewer/templates/base.html
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Upload</h1>
    <p class="lead">
    	<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="file" name="document">
	<button type="submit">Upload file</button>
</form>
    </p>
  </div>
</div>

viewer/templates/detail.html
<h1>{{ question_list.group_name }}</h1>
<ul>
{% for choice in question_list.question_set.all %}
    <img src='{{ choice.image.url }}' class="img-fluid" alt="Responsive image"/>
    <li>{{ choice.comment }}</li>
{% endfor %}
</ul>

viewer/templates/index.html
{% if group_list %}
    <ul>
    {% for item in group_list %}
        <li><a href="{{ item.id }}">{{ item.group_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}